# Generated by Django 4.0.3 on 2023-04-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='automobilevo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='technician',
            options={},
        ),
    ]
